import pool from "../config/db.js";

// ─────────────────────────────────────────────
// PROMPT QUERIES
// ─────────────────────────────────────────────

/**
 * Save a user's prompt to the prompts table.
 * Linked to a project via project_id (FK → projects.id CASCADE DELETE).
 *
 * @param {string} projectId - UUID of the parent project
 * @param {string} content   - The raw prompt text from the user
 * @returns {object} Newly created prompt row { id, project_id, content, created_at }
 */
export const savePrompt = async (projectId, content) => {
  const { rows } = await pool.query(
    `INSERT INTO prompts (project_id, content)
     VALUES ($1, $2)
     RETURNING id, project_id, content, created_at`,
    [projectId, content]
  );
  return rows[0];
};

/**
 * Fetch all prompts for a given project, ordered oldest first.
 * Useful for rebuilding the full conversation context.
 *
 * @param {string} projectId - UUID of the project
 * @returns {Array} Array of prompt rows
 */
export const getPromptsByProject = async (projectId) => {
  const { rows } = await pool.query(
    `SELECT id, content, created_at
     FROM prompts
     WHERE project_id = $1
     ORDER BY created_at ASC`,
    [projectId]
  );
  return rows;
};


// ─────────────────────────────────────────────
// GENERATION QUERIES
// ─────────────────────────────────────────────

/**
 * Save the AI-generated HTML output to the generations table.
 * Linked to a specific prompt via prompt_id (FK → prompts.id CASCADE DELETE).
 *
 * @param {string} promptId   - UUID of the parent prompt
 * @param {string} outputCode - The raw HTML code generated by the AI
 * @returns {object} Newly created generation row { id, prompt_id, output_code, created_at }
 */
export const saveGeneration = async (promptId, outputCode) => {
  const { rows } = await pool.query(
    `INSERT INTO generations (prompt_id, output_code)
     VALUES ($1, $2)
     RETURNING id, prompt_id, output_code, created_at`,
    [promptId, outputCode]
  );
  return rows[0];
};

/**
 * Fetch the most recent generation for a given prompt.
 * One prompt maps to one generation in the current schema.
 *
 * @param {string} promptId - UUID of the prompt
 * @returns {object|null} generation row or undefined
 */
export const getGenerationByPrompt = async (promptId) => {
  const { rows } = await pool.query(
    `SELECT id, output_code, created_at
     FROM generations
     WHERE prompt_id = $1
     ORDER BY created_at DESC
     LIMIT 1`,
    [promptId]
  );
  return rows[0];
};

/**
 * Fetch full generation history for a project.
 * Joins prompts + generations in a single query for the dashboard/history view.
 *
 * @param {string} projectId - UUID of the project
 * @returns {Array} Combined rows: { prompt_id, prompt_content, generation_id, output_code, generated_at }
 */
export const getGenerationHistory = async (projectId) => {
  const { rows } = await pool.query(
    `SELECT
       p.id           AS prompt_id,
       p.content      AS prompt_content,
       p.created_at   AS prompted_at,
       g.id           AS generation_id,
       g.output_code,
       g.created_at   AS generated_at
     FROM prompts p
     LEFT JOIN generations g ON g.prompt_id = p.id
     WHERE p.project_id = $1
     ORDER BY p.created_at DESC`,
    [projectId]
  );
  return rows;
};
